@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
chcp 65001
CLS

:CHOOSECURAVERSION
ECHO 3|4|5
CHOICE /C 3450 /N /M "0"
IF ERRORLEVEL 1 SET CURAVERSION=4.3
IF ERRORLEVEL 2 SET CURAVERSION=4.4
IF ERRORLEVEL 3 SET CURAVERSION=4.5
IF ERRORLEVEL 4 GOTO ENDOFTHESCRIPT
ECHO %CURAVERSION%

PAUSE

:ENDOFTHESCRIPT
